# Default configuration
server.port=8080
# trigger build 2
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Internal Service endpoint configs
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:5000/api/notify/send}
billing.service.url=${BILLING_SERVICE_URL:http://localhost:6000/api/billing/invoice}

#---
spring.config.activate.on-profile=dev

spring.datasource.url=jdbc:h2:mem:careflowdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

#---
spring.config.activate.on-profile=prod

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:careflow_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
